# Gunakan image Nginx resmi sebagai base image
FROM nginx:alpine

# Salin semua file dari direktori kerja lokal ke direktori root Nginx
COPY . /usr/share/nginx/html

# Expose port 80 untuk akses web
EXPOSE 80

# Jalankan Nginx di foreground
CMD ["nginx", "-g", "daemon off;"]
